import Image from 'next/image';
import Link from 'next/link';
import Meta from '../components/Meta';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import GoogleReviews from '../components/GoogleReviews';
import SDRPreview from '../components/SDRPreview';
import { trackCta } from './_app';

const levels = [
  { eyebrow: '01 · Eu ensino, você faz', title: 'Desafio Monetizar com IA', copy: '21 dias assíncronos para sair do consumo de ferramentas, encontrar dinheiro mal resolvido e testar uma forma de capturar valor.', outcome: 'Você termina com uma oportunidade priorizada e uma oferta ou solução testável.', href: '/desafio-monetizar-com-ia', cta: 'Conhecer o Desafio', image: '/covers/desafio-monetizar-com-ia.png' },
  { eyebrow: '02 · Eu faço com você', title: 'Sprint Vibe Seller', copy: '9 semanas de acompanhamento individual por WhatsApp, com checkpoints quinzenais para transformar uma oportunidade em projeto que anda.', outcome: 'Você executa com direção, prioridades e alguém para destravar as decisões que travam o projeto.', href: '/sprint-vibe-seller', cta: 'Ver o Sprint', image: '/covers/sprint-vibe-seller.png' },
  { eyebrow: '03 · Eu faço para você', title: 'Implementação Vibe Seller', copy: '9 semanas para eu construir a solução, entregar código e deixar uma operação pronta para vender, atender ou escalar.', outcome: 'Você recebe um ativo pronto para operar, com arquitetura e plano de escala documentados.', href: '/implementacao-vibe-seller', cta: 'Ver a Implementação', image: '/covers/implementacao-vibe-seller.png' },
];

const cases = [
  { name: 'Laboratório de Insights', lesson: 'Produto funcionando não é negócio sustentável.', copy: 'Chegou a cerca de 70 usuários, mas infraestrutura, retenção e uma feature crítica impediram a renovação.' },
  { name: 'Jurismart', lesson: 'Uma capacidade pode virar commodity antes do lançamento.', copy: 'Enquanto o produto era construído, o ChatGPT reduziu radicalmente o diferencial percebido pelos advogados.' },
  { name: 'Voice Dream', lesson: 'Tecnologia também vira ativo, valuation e equity.', copy: 'A solução construída com IA ajudou a criar empresa, viabilizar investimento seed e preservar 45% de equity do Felipe.' },
];

export default function Home() {
  return (
    <>
      <Meta title="Sistema Britto | Vibe Seller: rastrear, construir e capturar valor" description="Felipe Britto ajuda negócios a rastrear valor não capturado, construir a solução certa com IA e monetizar em receita, economia, margem ou equity." path="/" ogImage="/covers/desafio-monetizar-com-ia.png" />
      <Navbar />
      <main className="min-h-screen overflow-hidden bg-[#080b12] text-white">
        <section className="relative px-5 pb-20 pt-32 sm:px-8 sm:pt-40">
          <div aria-hidden="true" className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_14%_15%,rgba(163,255,18,.18),transparent_29%),radial-gradient(circle_at_82%_25%,rgba(112,71,255,.16),transparent_30%)]" />
          <div className="relative mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.1fr_.9fr]">
            <div>
              <p className="inline-flex rounded-full border border-[#a3ff12]/35 bg-[#a3ff12]/10 px-4 py-2 text-xs font-bold uppercase tracking-[.18em] text-[#c4ff72]">Felipe Britto · Vibe Seller</p>
              <h1 className="mt-7 max-w-4xl font-heading text-5xl font-black leading-[.94] tracking-[-.055em] sm:text-7xl xl:text-8xl">Saber Vibe Coding <span className="text-[#a3ff12]">não vai te deixar rico.</span></h1>
              <p className="mt-7 max-w-2xl text-lg leading-relaxed text-slate-300 sm:text-xl">Construir ficou barato. O dinheiro está em rastrear valor não capturado, escolher a solução certa e encontrar uma forma de monetizá-lo.</p>
              <div className="mt-9 flex flex-col gap-3 sm:flex-row">
                <Link href="#caminhos" className="min-h-12 rounded-xl bg-[#a3ff12] px-7 py-4 text-center font-extrabold text-black transition hover:-translate-y-0.5 hover:bg-[#c4ff72] focus-visible:outline focus-visible:outline-4 focus-visible:outline-[#a3ff12]/40">Encontrar meu próximo passo</Link>
                <Link href="#metodo" className="min-h-12 rounded-xl border border-white/15 px-7 py-4 text-center font-bold text-white transition hover:border-[#a3ff12]/60 focus-visible:outline focus-visible:outline-4 focus-visible:outline-white/30">Entender o método</Link>
              </div>
              <p className="mt-4 text-sm text-slate-400">IA é o meio. Receita, economia, margem ou equity são o fim.</p>
            </div>
            <div className="relative mx-auto w-full max-w-xl">
              <div aria-hidden="true" className="absolute -inset-8 rounded-[2.5rem] bg-[#a3ff12]/10 blur-3xl" />
              <Image src="/felipe-autoridade.webp" alt="Felipe Britto, fundador da Sistema Britto" width={960} height={960} priority className="relative aspect-square w-full rounded-3xl border border-white/10 object-cover shadow-2xl" />
              <div className="absolute -bottom-5 left-5 right-5 rounded-2xl border border-white/10 bg-[#101722]/95 p-5 shadow-2xl backdrop-blur"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#c4ff72]">A pergunta que muda tudo</p><p className="mt-2 font-heading text-xl font-bold">Onde existe valor que ninguém está capturando direito?</p></div>
            </div>
          </div>
        </section>

        <section id="metodo" className="border-y border-white/10 bg-[#0d1320] px-5 py-20 sm:px-8"><div className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-[.18em] text-[#c4ff72]">O método Vibe Seller</p><h2 className="mt-4 max-w-4xl font-heading text-4xl font-bold tracking-[-.04em] sm:text-6xl">Não comece pelo software. Comece pelo valor.</h2><div className="mt-12 grid gap-5 md:grid-cols-3">{[['01 · RASTREAR', 'Onde existe dinheiro mal resolvido?', 'Dor, desperdício, comprador e distribuição vêm antes de qualquer ferramenta.'], ['02 · VIBE CODAR', 'Qual é a menor solução que prova valor?', 'Construa, compre, adapte o processo ou ignore. IA não é a oportunidade.'], ['03 · MONETIZAR', 'Como esse valor será capturado?', 'Receita, economia, margem ou equity. SaaS é apenas uma das formas.']].map(([label, title, copy]) => <article key={label} className="rounded-3xl border border-white/10 bg-[#080b12] p-7"><p className="text-sm font-bold text-[#c4ff72]">{label}</p><h3 className="mt-5 font-heading text-2xl font-bold">{title}</h3><p className="mt-4 leading-relaxed text-slate-300">{copy}</p></article>)}</div></div></section>

        <section className="px-5 py-24 sm:px-8"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-sm font-bold uppercase tracking-[.18em] text-[#c4ff72]">Comece pelo gargalo</p><h2 className="mt-4 font-heading text-4xl font-bold tracking-[-.04em] sm:text-6xl">Nem toda oportunidade precisa virar um SaaS.</h2><p className="mt-5 text-lg leading-relaxed text-slate-300">A antiga home acertava ao começar pelo problema operacional. Mantivemos isso — agora sem empurrar uma ferramenta igual para todo mundo.</p></div><div className="mt-12 grid gap-5 lg:grid-cols-3"><article className="rounded-3xl border border-[#a3ff12]/25 bg-[#a3ff12]/[.05] p-7"><p className="text-sm font-bold uppercase tracking-[.14em] text-[#c4ff72]">Atender e vender</p><h3 className="mt-4 font-heading text-2xl font-bold">Lead esperando no WhatsApp é receita vazando.</h3><p className="mt-4 leading-relaxed text-slate-300">Se o problema é captar, qualificar, responder ou fazer follow-up, comece entendendo se uma operação de WhatsApp com IA resolve o gargalo.</p><Link href="/whatsapp" onClick={() => trackCta('/', 'VER WHATSAPP COM IA', 'gargalo-whatsapp')} className="mt-7 inline-flex font-bold text-[#c4ff72] hover:text-white">Ver WhatsApp com IA <span aria-hidden="true" className="ml-2">→</span></Link></article><article className="rounded-3xl border border-violet-300/25 bg-violet-300/[.05] p-7"><p className="text-sm font-bold uppercase tracking-[.14em] text-violet-200">Construir ou integrar</p><h3 className="mt-4 font-heading text-2xl font-bold">Você não deveria orçar código antes de definir o projeto.</h3><p className="mt-4 leading-relaxed text-slate-300">Na Sessão de Arquitetura, você sai com escopo, integrações, riscos e custos estimados — antes de decidir entre Sprint ou Implementação.</p><Link href="/sprint-vibe-seller" onClick={() => trackCta('/', 'COMPRAR SESSAO ARQUITETURA', 'gargalo-arquitetura')} className="mt-7 inline-flex font-bold text-violet-200 hover:text-white">Comprar sessão por R$ 150 <span aria-hidden="true" className="ml-2">→</span></Link></article><article className="rounded-3xl border border-cyan-300/25 bg-cyan-300/[.05] p-7"><p className="text-sm font-bold uppercase tracking-[.14em] text-cyan-200">Aprender a decidir</p><h3 className="mt-4 font-heading text-2xl font-bold">Quer executar sozinho sem construir no escuro?</h3><p className="mt-4 leading-relaxed text-slate-300">O Desafio organiza 21 dias de rastreio, construção e monetização para transformar uma hipótese em teste de mercado.</p><Link href="/desafio-monetizar-com-ia" onClick={() => trackCta('/', 'CONHECER DESAFIO', 'gargalo-desafio')} className="mt-7 inline-flex font-bold text-cyan-200 hover:text-white">Conhecer o Desafio <span aria-hidden="true" className="ml-2">→</span></Link></article></div></div></section>

        <section id="caminhos" className="px-5 py-24 sm:px-8"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-sm font-bold uppercase tracking-[.18em] text-[#c4ff72]">O nível certo para o seu momento</p><h2 className="mt-4 font-heading text-4xl font-bold tracking-[-.04em] sm:text-6xl">A mesma lógica. Três níveis de entrega.</h2><p className="mt-5 text-lg leading-relaxed text-slate-300">Você não precisa comprar mais software nem uma promessa genérica. Escolha quanto de execução quer assumir.</p></div><div className="mt-12 grid gap-6 lg:grid-cols-3">{levels.map((level, index) => <article key={level.title} className="group overflow-hidden rounded-3xl border border-white/10 bg-white/[.035] transition hover:-translate-y-1 hover:border-[#a3ff12]/50"><Image src={level.image} alt={`Capa ${level.title}`} width={1024} height={1024} className="aspect-square w-full object-cover" /><div className="p-6"><p className="text-xs font-bold uppercase tracking-wider text-[#c4ff72]">{level.eyebrow}</p><h3 className="mt-4 font-heading text-2xl font-bold transition group-hover:text-[#a3ff12]">{level.title}</h3><p className="mt-3 leading-relaxed text-slate-300">{level.copy}</p><p className="mt-5 border-l-2 border-[#a3ff12]/60 pl-3 text-sm leading-relaxed text-slate-200">{level.outcome}</p><Link href={level.href} onClick={() => trackCta('/', level.cta, `nivel-${index + 1}`)} className="mt-6 inline-flex min-h-11 items-center font-bold text-[#c4ff72] hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#a3ff12]">{level.cta} <span aria-hidden="true" className="ml-2">→</span></Link></div></article>)}</div></div></section>

        <section className="border-y border-[#a3ff12]/20 bg-[linear-gradient(120deg,rgba(163,255,18,.12),rgba(112,71,255,.10))] px-5 py-16 sm:px-8"><div className="mx-auto grid max-w-6xl items-center gap-8 lg:grid-cols-[1fr_auto]"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-[#c4ff72]">Porta de entrada do acompanhamento</p><h2 className="mt-3 font-heading text-3xl font-bold tracking-[-.04em] sm:text-5xl">Sprint e Implementação começam pela mesma conversa certa.</h2><p className="mt-5 max-w-3xl text-lg leading-relaxed text-slate-200">A Sessão de Arquitetura custa R$ 150 nesta semana (valor normal R$ 300, limitado às três primeiras agendas). Você sai com escopo, arquitetura e custos estimados. Se avançar para Sprint ou Implementação, os R$ 150 viram crédito.</p></div><Link href="/sprint-vibe-seller" onClick={() => trackCta('/', 'RESERVAR SESSAO ARQUITETURA', 'sessao-comum')} className="min-h-12 whitespace-nowrap rounded-xl bg-[#a3ff12] px-7 py-4 text-center font-extrabold text-black transition hover:bg-[#c4ff72] focus-visible:outline focus-visible:outline-4 focus-visible:outline-[#a3ff12]/40">Reservar sessão →</Link></div></section>

        <section id="whatsapp" className="px-5 py-24 sm:px-8"><div className="mx-auto grid max-w-6xl items-center gap-12 lg:grid-cols-[.95fr_1.05fr]"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-[#c4ff72]">Uma oportunidade recorrente</p><h2 className="mt-4 font-heading text-4xl font-bold tracking-[-.04em] sm:text-6xl">Lead que espera no WhatsApp é receita vazando.</h2><p className="mt-6 max-w-xl text-lg leading-relaxed text-slate-300">Se o gargalo é captar, qualificar, responder ou fazer follow-up, a solução pode ser uma operação de WhatsApp com IA — desde que ela faça sentido para sua margem, processo e volume.</p><Link href="/whatsapp" onClick={() => trackCta('/', 'VER WHATSAPP COM IA', 'whatsapp-proof')} className="mt-8 inline-flex min-h-12 items-center rounded-xl border border-[#a3ff12]/50 px-6 py-3 font-bold text-[#c4ff72] transition hover:border-[#a3ff12] hover:text-white">Ver WhatsApp com IA →</Link></div><SDRPreview /></div></section>

        <section className="border-y border-white/10 bg-[#0d1320] px-5 py-24 sm:px-8"><div className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-[.18em] text-[#c4ff72]">Experiência antes do nome</p><h2 className="mt-4 max-w-4xl font-heading text-4xl font-bold tracking-[-.04em] sm:text-6xl">A tese nasceu construindo, errando e capturando valor.</h2><div className="mt-12 grid gap-5 lg:grid-cols-3">{cases.map((item) => <article key={item.name} className="rounded-3xl border border-white/10 bg-[#080b12] p-7"><h3 className="font-heading text-2xl font-bold text-white">{item.name}</h3><p className="mt-4 font-semibold text-[#c4ff72]">{item.lesson}</p><p className="mt-4 leading-relaxed text-slate-300">{item.copy}</p></article>)}</div></div></section>

        <GoogleReviews />

        <section className="px-5 py-24 text-center sm:px-8"><div className="mx-auto max-w-4xl"><p className="text-sm font-bold uppercase tracking-[.18em] text-[#c4ff72]">Seu próximo passo</p><h2 className="mt-4 font-heading text-4xl font-black tracking-[-.04em] sm:text-6xl">Não procure ideias. Procure dinheiro mal resolvido.</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-relaxed text-slate-300">Comece sozinho no Desafio, execute acompanhado no Sprint ou deixe a construção comigo na Implementação.</p><Link href="#caminhos" className="mt-9 inline-flex min-h-12 items-center rounded-xl bg-[#a3ff12] px-8 py-4 font-extrabold text-black transition hover:bg-[#c4ff72] focus-visible:outline focus-visible:outline-4 focus-visible:outline-[#a3ff12]/40">Ver os três caminhos →</Link></div></section>
        <Footer />
      </main>
    </>
  );
}
